GET http://127.0.0.1:5000/movies/
Accept: application/json

###

GET http://127.0.0.1:5000/movies/?page=1
Accept: application/json

###

GET http://127.0.0.1:5000/movies/?genre_id=4
Accept: application/json

###

GET http://127.0.0.1:5000/movies/?year=2010
Accept: application/json

###

GET http://127.0.0.1:5000/directors/
Accept: application/json

###

GET http://127.0.0.1:5000/directors/1
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzMFx1MDQ0MVx1MDQzOFx1MDQzYlx1MDQzOFx1MDQzOSIsInBhc3N3b3JkIjoiUEBvaG84NzU4IiwiZXhwIjoxNjU5NDY0MDIwfQ.VwkoYD4b1MDhgfz3P0GPaGUgUr6_dU5gbbQxqlEpxV8

###

GET http://127.0.0.1:5000/genres/
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzMFx1MDQ0MVx1MDQzOFx1MDQzYlx1MDQzOFx1MDQzOSIsInBhc3N3b3JkIjoiUEBvaG84NzU4IiwiZXhwIjoxNjU5NDY0MDIwfQ.VwkoYD4b1MDhgfz3P0GPaGUgUr6_dU5gbbQxqlEpxV8

###

GET http://127.0.0.1:5000/genres/3
Accept: application/json

###

GET http://127.0.0.1:5000/movies/
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzMFx1MDQ0MVx1MDQzOFx1MDQzYlx1MDQzOFx1MDQzOS0yIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTc3NTQ2NDV9.1yV4_kdj_uZ7MeKhAP13_p4cp_mR3hW-xxxeIYQHY74

###

POST http://127.0.0.1:5000/movies/
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzMFx1MDQ0MVx1MDQzOFx1MDQzYlx1MDQzOFx1MDQzOS0yIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTc3NTQ2NDV9.1yV4_kdj_uZ7MeKhAP13_p4cp_mR3hW-xxxeIYQHY74
Content-Type: application/json

{
  "title": "Гарри Поттер мой кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1990,
  "rating": 10,
  "description": "10 из 10!"
}

###

PUT http://127.0.0.1:5000/movies/21
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQxMlx1MDQzMFx1MDQ0MVx1MDQzOFx1MDQzYlx1MDQzOFx1MDQzOS0yIiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTc3NTQ2NDV9.1yV4_kdj_uZ7MeKhAP13_p4cp_mR3hW-xxxeIYQHY74
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 12,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

PATCH http://127.0.0.1:5000/user/
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjEwa0BsaXN0LnJ1Iiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTgzNDYzNTB9.GfZtYanbgLCUnamt6Jk8xRhTpJmoFQnXItzFtdFxGRE
Content-Type: application/json

{
  "surname": "Башня",
  "name": "Крутая"
}

###

DELETE http://127.0.0.1:5000/movies/2
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Ilx1MDQyZVx1MDQzOFx1MDQ0Mlx1MDQ0ZiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1Nzc1NDExN30.4ouOSM0ACConvfmg9asQzraqh5fsKqLOOMCz4Iw23nk

###

GET http://127.0.0.1:5000/user/
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjEwa0BsaXN0LnJ1Iiwicm9sZSI6InVzZXIiLCJleHAiOjE2NTgyNjc2ODh9.V9rZMlD7JGIN1P8HygU4bMowFqQ6p8toOPu3c_FGLDk

###

POST http://127.0.0.1:5000/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email": "11k@list.ru",
  "password": "pioho875-",
  "role": "user",
  "surname": "Пупкин",
  "name": "Вася",
  "favorite_genre": 17
}

###
PUT http://127.0.0.1:5000/user/password/
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjlrQGxpc3QucnUiLCJyb2xlIjoidXNlciIsImV4cCI6MTY1ODM0NzM4NH0.mq8wskeAK0xxlgIPMb95kshyD62sBGWQQzNCehd2fZ4
Content-Type: application/json

{
  "password_old": "pioho875-",
  "password_new": "pioho8nl9"
}


###

DELETE http://127.0.0.1:5000/user/2

###

POST http://127.0.0.1:5000/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email": "9k@list.ru",
  "password": "pioho875-"
}

###

PUT http://127.0.0.1:5000/auth/login/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1rQGxpc3QucnUiLCJyb2xlIjoidXNlciIsImV4cCI6MTY2MDg0OTk4OH0.MH9bYW417nVPIHFaOHNseczYH7hlutm51pb4hzCciyQ"
}


###